// GENERATED by `npm run build` from the TypeScript source under src/ — do not edit by hand.
// Edit the .ts source and re-run the build instead; hand edits here will be overwritten.
"use strict";
(() => {
  // src/components/ascii-cursor.ts
  (function() {
    if (window.customElements && customElements.get("ascii-cursor")) return;
    const POOL = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*()_+{}[]|:;<>,.?/~";
    class AsciiCursor extends HTMLElement {
      constructor() {
        super(...arguments);
        this._up = false;
        this._cv = null;
        this._raf = 0;
        this._sraf = 0;
        this._onResize = null;
        this._onMove = null;
        this._onOut = null;
        this._onUp = null;
        this._onVis = null;
        this._onScroll = null;
      }
      connectedCallback() {
        if (this._up) return;
        if (window.matchMedia?.("(prefers-reduced-motion: reduce)").matches) return;
        this._up = true;
        const cv = this._cv = document.createElement("canvas");
        Object.assign(cv.style, { position: "absolute", inset: "0", width: "100%", height: "100%", display: "block" });
        this.appendChild(cv);
        const ctx = cv.getContext("2d");
        if (!ctx) return;
        const cell = Math.max(8, parseFloat(this.getAttribute("cell-size") || "") || 18);
        const radius = parseFloat(this.getAttribute("radius") || "") || 54;
        const density = parseFloat(this.getAttribute("density") || "") || 20;
        const hold = parseFloat(this.getAttribute("hold") || "") || 12;
        const boxColor = this.getAttribute("box-color") || "#E4622E";
        const textColor = this.getAttribute("text-color") || "#F1EADD";
        const fadeAttr = this.getAttribute("fade");
        const fadeTo = fadeAttr !== null ? parseFloat(fadeAttr) : 0.34;
        let w = 1, h = 1, cols = 1, rows = 1;
        let grid = [];
        let active = /* @__PURE__ */ new Set();
        const rebuild = () => {
          const dpr = Math.min(window.devicePixelRatio || 1, 2);
          w = Math.max(1, Math.round(this.getBoundingClientRect().width) || this.clientWidth || window.innerWidth);
          h = Math.max(1, Math.round(this.getBoundingClientRect().height) || this.clientHeight || window.innerHeight);
          cv.width = Math.floor(w * dpr);
          cv.height = Math.floor(h * dpr);
          ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
          cols = Math.ceil(w / cell) + 1;
          rows = Math.ceil(h / cell) + 1;
          grid = new Array(cols * rows);
          for (let i = 0; i < grid.length; i++) grid[i] = { char: " ", at: 0, delay: 0.05, dur: 0.25, hidden: false };
          active = /* @__PURE__ */ new Set();
        };
        rebuild();
        this._onResize = rebuild;
        window.addEventListener("resize", this._onResize);
        let mx = -1e4, my = -1e4, tx = -1e4, ty = -1e4;
        let touching = false;
        this._onMove = (e) => {
          touching = e.pointerType === "touch";
          mx = e.clientX;
          my = e.clientY;
        };
        this._onOut = () => {
          mx = -1e4;
          my = -1e4;
        };
        this._onUp = (e) => {
          if (e.pointerType === "touch") this._onOut?.();
        };
        window.addEventListener("pointermove", this._onMove, { passive: true });
        window.addEventListener("pointerup", this._onUp, { passive: true });
        window.addEventListener("pointercancel", this._onUp, { passive: true });
        document.addEventListener("pointerleave", this._onOut);
        let vis = true;
        this._onVis = () => {
          vis = !document.hidden;
        };
        document.addEventListener("visibilitychange", this._onVis);
        let inten = 1;
        const readScroll = () => {
          const vh = window.innerHeight || 1;
          const k = Math.min(1, Math.max(0, window.scrollY / (vh * 0.85)));
          inten = 1 - (1 - fadeTo) * k;
        };
        readScroll();
        this._onScroll = () => {
          if (!this._sraf) this._sraf = requestAnimationFrame(() => {
            this._sraf = 0;
            readScroll();
          });
        };
        window.addEventListener("scroll", this._onScroll, { passive: true });
        let last = performance.now();
        const frame = (now) => {
          this._raf = requestAnimationFrame(frame);
          if (!vis) {
            last = now;
            return;
          }
          const dt = Math.min(0.05, Math.max(0, (now - last) / 1e3));
          last = now;
          const t = now / 1e3;
          const ptx = tx, pty = ty;
          let moving = false;
          if (mx <= -1e4) {
            tx = -1e4;
            ty = -1e4;
          } else if (tx <= -1e4) {
            tx = mx;
            ty = my;
          } else {
            const dx = mx - tx, dy = my - ty;
            if (Math.abs(dx) > 0.1 || Math.abs(dy) > 0.1) {
              const ease = 1 - Math.exp(-dt / (touching ? 6e-4 : 4e-3));
              tx += dx * ease;
              ty += dy * ease;
              moving = true;
            } else {
              tx = mx;
              ty = my;
            }
          }
          if (moving) {
            const touchBoost = touching ? 1.55 : 1;
            const r = Math.max(1, radius * (0.6 + 0.4 * inten) * touchBoost);
            const rSq = r * r;
            const impact = density / 8 * inten * (touching ? 1.6 : 1);
            const holdScale = Math.max(0.1, hold / 10);
            const segDx = tx - ptx, segDy = ty - pty;
            const segLen = Math.sqrt(segDx * segDx + segDy * segDy);
            const steps = touching ? Math.min(8, Math.max(1, Math.ceil(segLen / (cell * 0.6)))) : 1;
            for (let s = 0; s < steps; s++) {
              const k = steps === 1 ? 1 : s / (steps - 1);
              const px = ptx + segDx * k, py = pty + segDy * k;
              const c0 = Math.max(0, Math.floor((px - r) / cell)), c1 = Math.min(cols - 1, Math.ceil((px + r) / cell));
              const r0 = Math.max(0, Math.floor((py - r) / cell)), r1 = Math.min(rows - 1, Math.ceil((py + r) / cell));
              for (let c = c0; c <= c1; c++) {
                for (let rw = r0; rw <= r1; rw++) {
                  const dx = px - (c * cell + cell / 2), dy = py - (rw * cell + cell / 2);
                  const dSq = dx * dx + dy * dy;
                  if (dSq >= rSq) continue;
                  const falloff = Math.pow(1 - Math.sqrt(dSq) / r, 1.5);
                  if (Math.random() >= falloff * impact) continue;
                  const idx = c * rows + rw, g = grid[idx];
                  if (!g) continue;
                  if (g.at === 0 || t - g.at > 0.2) {
                    g.delay = (0.03 + Math.random() * 0.05) * holdScale;
                    g.dur = (0.1 + Math.random() * 0.15) * holdScale;
                    g.hidden = Math.random() < 0.04;
                  }
                  g.at = t;
                  if (g.char === " " || Math.random() < 0.15) g.char = POOL[Math.random() * POOL.length | 0];
                  active.add(idx);
                }
              }
            }
          }
          ctx.clearRect(0, 0, w, h);
          ctx.font = "600 " + (cell - 6) + "px monospace";
          ctx.textAlign = "center";
          ctx.textBaseline = "middle";
          ctx.globalAlpha = 0.35 + 0.65 * inten;
          const scramble = 1 - Math.exp(-7.2 * dt);
          for (const idx of active) {
            const g = grid[idx];
            if (!g || g.at === 0) {
              active.delete(idx);
              continue;
            }
            const el = t - g.at;
            if (el >= g.delay + g.dur) {
              g.char = " ";
              g.at = 0;
              g.hidden = false;
              active.delete(idx);
              continue;
            }
            if (g.hidden) continue;
            const c = Math.floor(idx / rows), rw = idx % rows;
            if (el >= g.delay && Math.random() < scramble) g.char = POOL[Math.random() * POOL.length | 0];
            const x = c * cell, y = rw * cell;
            ctx.fillStyle = boxColor;
            ctx.fillRect(x, y, cell, cell);
            ctx.fillStyle = textColor;
            ctx.fillText(g.char, x + cell / 2, y + cell / 2);
          }
          ctx.globalAlpha = 1;
        };
        this._raf = requestAnimationFrame(frame);
      }
      disconnectedCallback() {
        cancelAnimationFrame(this._raf);
        if (this._sraf) cancelAnimationFrame(this._sraf);
        if (this._onResize) window.removeEventListener("resize", this._onResize);
        if (this._onMove) window.removeEventListener("pointermove", this._onMove);
        if (this._onUp) {
          window.removeEventListener("pointerup", this._onUp);
          window.removeEventListener("pointercancel", this._onUp);
        }
        if (this._onScroll) window.removeEventListener("scroll", this._onScroll);
        if (this._onOut) document.removeEventListener("pointerleave", this._onOut);
        if (this._onVis) document.removeEventListener("visibilitychange", this._onVis);
        this._up = false;
      }
    }
    customElements.define("ascii-cursor", AsciiCursor);
  })();
})();
