// Build script for the "Oficina Digital" portfolio.
//
// The runtime this project ships to (`support.js`, a vendored Design
// Component engine) has no build step of its own: `components/*.js` are
// loaded via plain `<script src>` tags, and the page's own logic
// (`class Component extends DCLogic`) is executed straight out of a
// `<script data-dc-script>` tag via `new Function(...)` — neither can run
// TypeScript or ES module `import`/`export` syntax directly.
//
// So the TypeScript source under `src/` is the thing to edit; this script
// is what turns it back into the flat, import-free JavaScript the browser
// actually runs:
//   1. Each `src/components/*.ts` custom element is bundled standalone
//      (IIFE, no cross-file deps besides DOM lib types) → `components/*.js`.
//   2. `src/logic/component.ts` — which DOES import from `src/data`,
//      `src/types`, etc. — is bundled to flat ESM (so esbuild can inline
//      every import into one file with no wrapper function), then the
//      trailing `export { Component };` line is stripped, because the DC
//      runtime expects to find a bare top-level `Component` identifier in
//      the script it evaluates, not a module export.
//   3. That flattened script is spliced into
//      `Portfolio Andre Ricco.dc.html`'s `<script data-dc-script>` tag,
//      leaving everything else in the file (markup, `data-props`, styles)
//      untouched.
//
// Run via `npm run build` (→ `tsx scripts/build.ts`). Run `npm run
// typecheck` first (or `npm run verify` for both) — this script only
// bundles; it does not type-check.

import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import * as esbuild from 'esbuild';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '..');

const GENERATED_BANNER =
  '// GENERATED by `npm run build` from the TypeScript source under src/ — do not edit by hand.\n' +
  '// Edit the .ts source and re-run the build instead; hand edits here will be overwritten.\n';

/** Standalone custom elements: no cross-file imports, bundled as a self-registering IIFE. */
const COMPONENTS: readonly string[] = ['pixel-reveal', 'ascii-cursor', 'image-slot'];

async function buildComponents(): Promise<void> {
  for (const name of COMPONENTS) {
    const entry = path.join(root, 'src', 'components', `${name}.ts`);
    const outfile = path.join(root, 'components', `${name}.js`);
    const result = await esbuild.build({
      entryPoints: [entry],
      bundle: true,
      format: 'iife',
      platform: 'browser',
      target: 'es2020',
      write: false,
      logLevel: 'silent',
      // These ship as-is to every visitor's browser (plain <script src>,
      // no further bundler downstream) — minifying is a pure transfer-size
      // win with no behavior change, so there's no reason to skip it.
      minify: true,
    });
    const [file] = result.outputFiles;
    if (!file) throw new Error(`esbuild produced no output for ${entry}`);
    await writeFile(outfile, GENERATED_BANNER + file.text, 'utf8');
    console.log(`  components/${name}.js  (${file.text.length.toLocaleString()} bytes)`);
  }
}

/** Strips the trailing `export { Component };`-style statement esbuild's ESM
 *  output ends with, so the result is a bare top-level `var Component = …`
 *  the DC runtime's `new Function(...)` can find via `typeof Component`. */
function stripTrailingExport(bundled: string): string {
  const stripped = bundled.replace(/\n*export\s*\{\s*Component\s*\};\s*$/, '\n');
  if (stripped === bundled) {
    throw new Error(
      'Expected the Component bundle to end with `export { Component };` — ' +
      'did src/logic/component.ts stop exporting `Component`, or does esbuild\'s ' +
      'output shape need updating here?'
    );
  }
  return stripped;
}

async function buildDcLogic(): Promise<string> {
  const entry = path.join(root, 'src', 'logic', 'component.ts');
  const result = await esbuild.build({
    entryPoints: [entry],
    bundle: true,
    format: 'esm',
    platform: 'browser',
    target: 'es2020',
    write: false,
    logLevel: 'silent',
    // Same rationale as buildComponents(): this is the actual script every
    // visitor's browser evaluates, not a human-edited region of the
    // .dc.html (see the README's "Regras de estilo do arquivo") — so
    // minifying it is free size-wise. `minifyIdentifiers` is deliberately
    // left off, though: it renames the top-level `Component` binding this
    // whole build step depends on (stripTrailingExport below, and the DC
    // runtime's own `new Function(...)` lookup) to something like `M`,
    // which breaks both silently rather than through a type error.
    minifyWhitespace: true,
    minifySyntax: true,
  });
  const [file] = result.outputFiles;
  if (!file) throw new Error(`esbuild produced no output for ${entry}`);
  return stripTrailingExport(file.text);
}

const DC_SCRIPT_RE = /(<script type="text\/x-dc" data-dc-script[^>]*>)[\s\S]*?(<\/script>)/;

async function injectDcLogic(bundledJs: string): Promise<string> {
  const htmlPath = path.join(root, 'Portfolio Andre Ricco.dc.html');
  const html = await readFile(htmlPath, 'utf8');
  if (!DC_SCRIPT_RE.test(html)) {
    throw new Error(`Could not find <script data-dc-script> in ${htmlPath} — is the file structure unchanged?`);
  }
  const injected = '\n' + GENERATED_BANNER + '\n' + bundledJs.trim() + '\n';
  const nextHtml = html.replace(DC_SCRIPT_RE, (_match, open: string, close: string) => open + injected + close);
  await writeFile(htmlPath, nextHtml, 'utf8');
  console.log(`  Portfolio Andre Ricco.dc.html  (<script data-dc-script> replaced, ${bundledJs.length.toLocaleString()} bytes)`);
  return nextHtml;
}

/** Static hosts (Netlify, GitHub Pages, Vercel static, …) serve whatever sits
 *  at `/index.html` — they don't know to look for a file named
 *  `Portfolio Andre Ricco.dc.html` with a space and a custom extension in
 *  it. Mirroring the exact same bytes to `index.html` is what makes the
 *  deployed root URL actually resolve, instead of a 404. */
async function writeIndexHtml(html: string): Promise<void> {
  const indexPath = path.join(root, 'index.html');
  await writeFile(indexPath, html, 'utf8');
  console.log(`  index.html  (mirror of Portfolio Andre Ricco.dc.html, for static hosting)`);
}

async function main(): Promise<void> {
  console.log('Bundling components…');
  await buildComponents();
  console.log('Bundling DC logic…');
  const bundledJs = await buildDcLogic();
  console.log('Injecting into Portfolio Andre Ricco.dc.html…');
  const html = await injectDcLogic(bundledJs);
  await writeIndexHtml(html);
  console.log('Done.');
}

main().catch((err: unknown) => {
  console.error(err);
  process.exitCode = 1;
});
